### ISSUE TITLE
Process.removeChild() creates orphans?

### ISSUE THREAD

**Issue by jstolarek** [deepnight/deepnightLibs#10]
Not sure if I'm reading this correctly, but I think `Process.removeChild()` might be creating orphans:

```haxe
public function removeChild( p : Process ) {
	if( p.parent != this ) throw "invalid parent access";
	p.parent = null;
	children.remove(p);
}
```
Shouldn't there also be `ROOTS.push( p );` ?

**Comment by deepnight** [comment]
This would lead to some confusions, as the expected behavior would be to also dispose/destroy the removed child process.

I added a separate method to promote a child process to global, and renamed the ``removeChild`` to ``removeAndDestroyChild``
