### ISSUE TITLE
[Optimization] UnitTests Action doesn't actually reference the 'matrix' values

### ISSUE THREAD

**Issue by wolfkabal** [deepnight/deepnightLibs#31]
https://github.com/deepnight/deepnightLibs/blob/22d2b54fa1507277e78bd594a3ad62ee5d0b930f/.github/workflows/runUnitTests.yml#L26

The `setup-haxe` doesn't actually use the `matrix` reference directly. Instead hard coding the Haxe version.

Instead, the `haxe-version:` should reference `${{ matrix.haxe }}`. This will ensure any changes to the required version can be made in one spot, within the `matrix` directly, as well as supporting multiple versions of Haxe for testing if needed.

```
 - uses: krdlab/setup-haxe@v1
    with:
      haxe-version: ${{ matrix.haxe }}
```

**Comment by deepnight** [comment]
Oh very interesting fix, thank you :) I don't know much about GH actions, and this totally makes sense. Good to know :)

**Comment by tdonaworth** [comment]
Yeah, this makes it possible to actually test out multiple versions, that's the core use of the `matrix`.

So this would ensure that your test, or whatever you're doing in your action, runs on all three versions, independently. Great for backwards, and RC testing. 😄 
It basically just creates an array to pass into whatever parameter you want, in your case, `haxe-version`.
```
strategy:
      matrix:
        os: [windows-latest]
        haxe: [3.4.7 , 4.2.0, 4.2.5]
```

Kudos, and thanks for the great work, just discovered your gameBase template 🤯

**Comment by wolfkabal** [comment]
Yeah, `matrix` can be great for testing multiple versions of something. So instead of duplicating your test for say version 3.4.7 and 4.2.5 (legacy and current), you setup the matrix. This will then loop over the `step` based on the number of elements in the `matrix` and run that `step` multiple times, passing in the values.

example:
```
    strategy:
      matrix:
        os: [windows-latest]
        haxe: [3.4.7, 4.2.0, 4.2.5]
```
In your case, this would run your steps three times, passing in each version number to
```
- uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
```
This way you will run your tests in three separate `setup-haxe` environments, each with their own version 😄
