### ISSUE TITLE
Breaks with haxe nightly

### ISSUE THREAD

**Issue by kLabz** [deepnight/deepnightLibs#6]
Firstly, thanks for this and gameBase :)

Currently, this lib cannot be used with [recent] haxe nightlies because of https://github.com/deepnight/deepnightLibs/blob/master/src/dn/heaps/Controller.hx#L83 which is some kind of semi qualified module access and isn't supported in latest haxe (and probably in soonish-to-be-released 4.1.0).

I may find some time to make a PR soon but not today.

**Comment by kLabz** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/commit/d044621c716a36473bedbbe3bbbecf5197fcd0d7 :)

**Comment by deepnight** [comment]
Thank you!
